### ISSUE TITLE
feat : social media profile integration with the name of the core team member

### ISSUE THREAD

**Issue by subhadeepbanerjee2003** [GDSC-Jadavpur-University/GDSC-JU-Website#106]
-- **`Proposed feature`**

- The name of the core team member should be integrated with their any  social media profile 
-  eg : ***`LinkedIn`*** or ***`Twitter`*** or ***`GitHub`***
- With this feature any one `connect` with them via socia media and can gather more info about GDSC - Jadavpur University.

**Comment by like-rounak** [comment]
Please Assign this issue to me . I am ready to work upon it . @Ayushpanditmoto

**Comment by subhadeepbanerjee2003** [comment]
@like-rounak i would like to work as I have opened it.

**Comment by subhadeepbanerjee2003** [comment]
@Ayushpanditmoto assign this to other contributors

**Comment by SristiDakua** [comment]
I'm working on it.

**Comment by subhadeepbanerjee2003** [comment]
@SristiDakua raise an issue and move forward
