### ISSUE TITLE
[Bug] : Add margin in about section for better user interface   

### ISSUE THREAD

**Issue by ankitjhagithub21** [GDSC-Jadavpur-University/GDSC-JU-Website#108]
![image](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/91364014/b359b2e9-eb7e-41a2-9fcc-43ff4f4f5947)

**Comment by Deb-cybe** [comment]
Hey there, assign this issue to me.

**Comment by Ayushpanditmoto** [comment]
@Deb-cybe already assigned to someone else but make sure you star the repo 1st then search for more issues we have

**Comment by Bib3k4u** [comment]
Is it still open, Can I work on this?
