### ISSUE TITLE
[Bug]/Google maps not loading in "Placement | Intern Talk With Vivek Gupta" webpage

### ISSUE THREAD

**Issue by Michael-G-Scott** [GDSC-Jadavpur-University/GDSC-JU-Website#142]
It is showing "This site can't load google maps correctly" in "Placement | Intern Talk With Vivek Gupta" web page under events section

**Comment by like-rounak** [comment]
Could u share screenshot

**Comment by like-rounak** [comment]
Are you talking about this webpage - https://gdsc.community.dev/events/details/developer-student-clubs-jadavpur-university-kolkata-presents-placement-intern-talk-with-vivek-gupta/ 
?

**Comment by Michael-G-Scott** [comment]
Yes here the Google map was not showing at that time

**Comment by like-rounak** [comment]
It is a different site , unrelated to this . anyways , since its fixed now . Please close the issue .
