### ISSUE TITLE
[Bug]: There is a bug in update Readme file

### ISSUE THREAD

**Issue by Basavarajakjbasuu** [GDSC-Jadavpur-University/GDSC-JU-Website#143]
Could you please update Readme.md file. Instead running ```npm run dev``` first should install respected packages this commend is not there in file 

Sol:
```
npm install
# or
yarn add
# or
pnpm add
# or
bun add
```

**Comment by DasSohamOfficial** [comment]
please assign it to me

**Comment by Basavarajakjbasuu** [comment]
Could you please Assign to me

**Comment by Xzm27** [comment]
No need to assign just update and make a pull request
