### ISSUE TITLE
Subscribe page Issue ( Images not loading )

### ISSUE THREAD

**Issue by like-rounak** [GDSC-Jadavpur-University/GDSC-JU-Website#152]
![image](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/78261692/1507a99b-32ca-404d-a3cc-b8d1299030ec)

**Comment by VivekHalder** [comment]
I want to work on this issue.

**Comment by Rawshansharma** [comment]
can i work on this issue ??

**Comment by lokeshsingh3721** [comment]
i can work on this issue , can you please assign it to me ?
