### ISSUE TITLE
Events Page ( Containers uneven ) , Image not loading 

### ISSUE THREAD

**Issue by like-rounak** [GDSC-Jadavpur-University/GDSC-JU-Website#153]
![image](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/78261692/9800ece9-f47e-4fb9-b21c-bd303cbce8e3)

**Comment by akrai15** [comment]
pls assign this to me, pr ready to merge.

**Comment by akrai15** [comment]
![Screenshot 2023-10-04 161307](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/139689257/21b46161-b70d-40c1-9b47-8b34a42feedd)
