### ISSUE TITLE
Change This Image to Another Image with background Transparent .png Format

### ISSUE THREAD

**Issue by Ayushpanditmoto** [GDSC-Jadavpur-University/GDSC-JU-Website#171]
![Screenshot_8](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/31253617/94317a5c-8a28-4e1a-ba04-6c16ad195bd4)

**Comment by notpritam** [comment]
can you assign this to me...

**Comment by FreemRL** [comment]
Hi I created a PR for this :) (#172)
