### ISSUE TITLE
Modal/ ligthbox in gallery

### ISSUE THREAD

**Issue by Xzm27** [GDSC-Jadavpur-University/GDSC-JU-Website#178]
Create a modal or lightbox in gallery section to show enlarged image.

**Comment by ManishMadan2882** [comment]
**I can work on this one**

**Comment by DevJobalia** [comment]
if you merge request I could work ahead to make it light-dark mode compatible

**Comment by DevJobalia** [comment]
What next step should I perform

**Comment by DevJobalia** [comment]
Can we close this issue? @Ayushpanditmoto
