### ISSUE TITLE
[Feature , Improvement] Navbar Hover + active page

### ISSUE THREAD

**Issue by like-rounak** [GDSC-Jadavpur-University/GDSC-JU-Website#203]
Before : 
![image](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/78261692/b3197c8c-7ee6-4958-b324-96a67e4a7e19)
After 
![image](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/78261692/23b87059-2d6b-4ba9-bb00-99dee6397bb9)

**Comment by Lazy-Coder-03** [comment]
can u give a little more insights of this improvement?

**Comment by Lazy-Coder-03** [comment]
@like-rounak Okay understood so u have already Finished working on it i guess
