### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by aindree-2005** [GDSC-Jadavpur-University/GDSC-JU-Website#211]
Currently, we donot have a dedicated FAQ page. A lot of times, people have queries about GDSC's goals and ideals, if it same as CodeClub JU, time commitments for those willing to join and so on. This brought to my mind that a dedicated FAQ page could solve  a number of these problems.

@Ayushpanditmoto is this an issue I could work on?

**Comment by Ayushpanditmoto** [comment]
Can we add this things in home screen or create a new faq page which one will be better

**Comment by aindree-2005** [comment]
Actually, I was thinking of an 8th page, just for symmetry of colours in the navbar. But GDSC's official website has FAQ on homepage

**Comment by Ayushpanditmoto** [comment]
@aindree-2005  i think we don't need so many pages you can add FAQ in home page use nextui https://nextui.org/docs/components/accordion

**Comment by aindree-2005** [comment]
Got it!
