### ISSUE TITLE
A little bug was there the declared variable and the used variable were different in the components for the footer, I am providing the screenshot below  .

### ISSUE THREAD

**Issue by dipak-01** [GDSC-Jadavpur-University/GDSC-JU-Website#249]
![Screenshot 2023-10-11 032609](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/120103598/ba20b204-c70e-4c3d-bd52-b16eb187e749)
I am making a pull request,  
If possible lable it as hactoberfest  and merge it.

**Comment by dipak-01** [comment]
The FaxTwitter and the FaTwitter

**Comment by KushalSr** [comment]
It is resolved?

**Comment by dipak-01** [comment]
Yes I made the PR and its already merge. You can close this issue.
