### ISSUE TITLE
Homepage Not Responsive: User Experience Problem

### ISSUE THREAD

**Issue by shouryasinghrathore** [GDSC-Jadavpur-University/GDSC-JU-Website#27]
![gdsc-ju vercel app_](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/83858748/287f27d2-63f7-4ad5-b32f-7bb85f5e3c2c)

Hii  @Ayushpanditmoto 
Please assign this issue to me and also add the Hacktoberfest label.

**Comment by Ayushpanditmoto** [comment]
@shouryasinghrathore  assigned

**Comment by shouryasinghrathore** [comment]
@Ayushpanditmoto  
I made the landing pages and form fields responsive
