### ISSUE TITLE
Navigation button missing for mobile view

### ISSUE THREAD

**Issue by GrandmasterGogo** [GDSC-Jadavpur-University/GDSC-JU-Website#34]
**Issue** : Navigation button missing in the header for mobile view
**Solution** : A 3 horizontal line button (hamburger button) on the header which opens up a sidebar containing links to different pages .

**Comment by GrandmasterGogo** [comment]
I would like to solve this issue . Pls assign it to me .

**Comment by Xzm27** [comment]
Assigned

**Comment by like-rounak** [comment]
@Xzm27 
Issue Solved by @akrai15 

Please Close this issue

**Comment by GrandmasterGogo** [comment]
Since the problem has already been solved , can you please close this issue ?
