### ISSUE TITLE
Add These Link in Icons in Footer

### ISSUE THREAD

**Issue by Ayushpanditmoto** [GDSC-Jadavpur-University/GDSC-JU-Website#67]
Github - https://github.com/GDSC-Jadavpur-University/
Instagram -  https://www.instagram.com/gdsc_ju/
Linkedin - https://www.linkedin.com/company/gdsc-jadavpur-university/

**Comment by Kokonodray2001** [comment]
@Ayushpanditmoto can you assign this issue to me?

**Comment by Kokonodray2001** [comment]
I have created the PR for this issue https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/pull/73
