### ISSUE TITLE
Header Alignments issues

### ISSUE THREAD

**Issue by Ayushpanditmoto** [GDSC-Jadavpur-University/GDSC-JU-Website#68]
![Screenshot_3](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/31253617/9f4caf62-ffcb-4bf5-9ff2-ba7a2f238993)

**Comment by viditagrawal56** [comment]
i would like to work on this issue
Please assign it to me

**Comment by akrai15** [comment]
Pls assign this  issue to me, i can realign this issue.

**Comment by viditagrawal56** [comment]
@Ayushpanditmoto you have deleted the navbar component. Do i have to create a new one?
