### ISSUE TITLE
Create routes for the team, events and projects pages.

### ISSUE THREAD

**Issue by Xzm27** [GDSC-Jadavpur-University/GDSC-JU-Website#7]
Add routes for teams, events and projects pages. Also add links for each into the navbar.

**Comment by akadeepesh** [comment]
I can do this, please assign it to me!

**Comment by Xzm27** [comment]
Just create a pr when you are done

**Comment by akadeepesh** [comment]
I just checked that it is successfully routing through navbar to projects, events and team page. What is the query can you explain me so that I can work on that

**Comment by Ayushpanditmoto** [comment]
@Xzm27  already added bro lol

**Comment by Ayushpanditmoto** [comment]
I am closing this issue
