### ISSUE TITLE
Add Subscription Page

### ISSUE THREAD

**Issue by sau-mili** [GDSC-Jadavpur-University/GDSC-JU-Website#72]
I would like to add a subscription page.

**Comment by sau-mili** [comment]
I mean, subscribe to newsletter kind of thing. Almost every organizations keep record of emails, to send notifications about events and stuff.

**Comment by sau-mili** [comment]
Oh that I will update.. based on the landing page

**Comment by sau-mili** [comment]
![Screenshot 2023-10-03 235859](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/146661411/decbd35a-d828-4454-b8a2-bad79ba0ab21)

Check this out please..

**Comment by Ayushpanditmoto** [comment]
@sau-mili its good where you want to add this ??

**Comment by sau-mili** [comment]
navigation bar , or footer?

**Comment by sau-mili** [comment]
![Screenshot 2023-10-04 010114](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/146661411/a956d0b4-4f22-4982-a545-e82135e6721e)
![Screenshot 2023-10-04 010153](https://github.com/GDSC-Jadavpur-University/GDSC-JU-Website/assets/146661411/d6163a22-1ecf-452a-8a9e-8de701bcdff3)


Check this out

**Comment by Ayushpanditmoto** [comment]
@sau-mili now looks good

**Comment by sau-mili** [comment]
Added Pull request.

**Comment by sau-mili** [comment]
#125 
Will you add this pull request to hacktober?

**Comment by Ayushpanditmoto** [comment]
Done @sau-mili
