### ISSUE TITLE
In Gallery Page

### ISSUE THREAD

**Issue by Ayushpanditmoto** [GDSC-Jadavpur-University/GDSC-JU-Website#86]
Add Demo Images With Framer Motion Package 
Make Sure all the Components Reusable Type

**Comment by oitashg** [comment]
please assign me

**Comment by ankitjhagithub21** [comment]
please assign me

**Comment by Ayushpanditmoto** [comment]
@ankitjhagithub21  its Already assigned to someone else you can see many new issues and make sure star the repo before starting

**Comment by ankitjhagithub21** [comment]
okay

**Comment by like-rounak** [comment]
@Ayushpanditmoto I think the issue can be closed . Should I add more images in Gallery ?

**Comment by Ayushpanditmoto** [comment]
@like-rounak you have more images ??

**Comment by like-rounak** [comment]
My bad , I just checked , all are added and no extra are left .
